### ISSUE TITLE
[Question] How to generate a merge file and a vocab file

### ISSUE THREAD

**Issue by Zhang-kg** [microsoft/Megatron-DeepSpeed#123]
I want to use the Megatron framework for Chinese NLP pre-training tasks. Currently, I have Chinese corpus resources and a vocab.txt file. However, for most frameworks, it seems that vocab.json and merge.txt are needed. Can I generate the above two files from Chinese corpus resources? If so, how can I generate them? Sorry, I haven't found a particularly suitable tutorial on Google.

**Comment by whalefa1I** [comment]
extract it from the tokenizer model

**Comment by lonelydancer** [comment]
@Zhang-kg do you have any idea?
