### ISSUE TITLE
Which data loading strategy is the fastest? cached , mmap, or lazy?

### ISSUE THREAD

**Issue by 2catycm** [microsoft/Megatron-DeepSpeed#133]
Which data loading strategy is the fastest? cached , mmap, or lazy? Or, what aspect it depends on machines?
There isn't any documentation on this, and I cannot understand how they work respectively. On the Internet I found that mmap is memory map, a system call to pin the data content from disk to memory, but what is "cached"?

Besides, why do we need to specify the way of loading strategy in `preprocess_data.py`？ I thought it was just about how to load data, but not about how to preprocess it.

**Comment by conglongli** [comment]
Both data loading and preprocess_data are mostly written by https://github.com/NVIDIA/Megatron-LM where we forked from. We mostly only used the default mmap which worked fine. If you are interested in this part, you can either do some simple comparison by training a model with all 3 strategies, and/or ask for further clarification at https://github.com/NVIDIA/Megatron-LM.
