### ISSUE TITLE
Missing optimizer param_group name

### ISSUE THREAD

**Issue by nikit91** [microsoft/Megatron-DeepSpeed#174]
Hi,
In the file `megatron/optimizer/__init__.py`:

**Current version:**
https://github.com/microsoft/Megatron-DeepSpeed/blob/d04f37097cd9afe502050b91272b741117e95642/megatron/optimizer/__init__.py#L18-L66

 the `param_group` attribute `'name'` was removed
 
**Older Version:** https://github.com/microsoft/Megatron-DeepSpeed/blob/178beeb45d8f89c926366659900934351aa007e6/megatron/optimizer/__init__.py#L30-L52

This causes the MoE Utils https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/moe/utils.py#L94 to throw a `KeyError`. 

What do you suggest can be done? Will it be fine if I assign these param groups a unique identifier on my own?

**Comment by conglongli** [comment]
@nikit91 Thanks for reporting the issue. Yes I think it's fine to simply add a name to each param_group in the new code. For example, change `param_groups.append({'params': wd_no_scale_lr, 'wd_mult': 1.0, 'lr_mult': 1.0})` to `param_groups.append({'params': wd_no_scale_lr, 'wd_mult': 1.0, 'lr_mult': 1.0, 'name' : 'wd_no_scale_lr'})` and same as the other three. Could you try on your end if that solve your issue, and if so could you create a PR? Thank you.

**Comment by nikit91** [comment]
@conglongli Thanks for your quick response. The proposed solution seems to have solved the issue, I have raised a PR for the same :)
