### ISSUE TITLE
MoE Model size estimation

### ISSUE THREAD

**Issue by anon-nlp-dev** [microsoft/Megatron-DeepSpeed#187]
Is there a formula for model size estimation for the mixture of experts based model?

I was looking at the model variants in the following blog, and wondered if there's a formula to compute the model size for the GPT variants: https://www.microsoft.com/en-us/research/blog/deepspeed-advancing-moe-inference-and-training-to-power-next-generation-ai-scale#our-moe-based-nlg-model-architecture

**Comment by clumsy** [comment]
Consider using [DeepSpeed FLOPS profiler](https://www.deepspeed.ai/tutorials/flops-profiler/) where MoE parameter count has been added recently: https://github.com/microsoft/DeepSpeed/pull/3720

**Comment by clumsy** [comment]
Which DeepSpeed version are you using, @anon-nlp-dev?
`group_name` is accessed only after `getattr` check - so there should be no `AttributeError` error.
Can you also please attach the traceback?

**Comment by clumsy** [comment]
@anon-nlp-dev that's not surprising, look at the model layers breakdown. Your model is fully dense as it only has `ParallelMLP`, no `MoE` layers.
