### ISSUE TITLE
[BUG] pretrain_gpt.py: error: unrecognized arguments: --local_rank

### ISSUE THREAD

**Issue by nrailgun** [microsoft/Megatron-DeepSpeed#194]
I tried the [GPT demo](https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples_deepspeed/rebase/ds_pretrain_gpt_125M.sh) and I got

![image](https://github.com/microsoft/Megatron-DeepSpeed/assets/14273895/a26633d6-abb8-42c8-bb2f-1bf7a606d5f3)

I guess the deepspeed launcher passed args `local_rank=x`, which actually is `local-rank=x`...

**Comment by conglongli** [comment]
This was fixed recently. Please make sure to always try `git pull`
