### ISSUE TITLE
ImportError: cannot import name '_parse_args' from 'megatron.global_vars'

### ISSUE THREAD

**Issue by coorful** [microsoft/Megatron-DeepSpeed#205]
emm, eval_harness script cause an error, it seems deepspeed evaluation process is not ready..
Traceback (most recent call last):
  File "../../tasks/eval_harness/evaluate.py", line 402, in <module>
    from megatron.global_vars import _parse_args
ImportError: cannot import name '_parse_args' from 'megatron.global_vars' @conglongli

**Comment by SefaZeng** [comment]
It seems the `evaluate.py` is still in an old version, I meet the same issue.
