### ISSUE TITLE
what are the default llama sizes

### ISSUE THREAD

**Issue by 152334H** [microsoft/Megatron-DeepSpeed#217]
in the llama/2 pretraining scripts:

https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples_deepspeed/pretrain_llama_distributed.sh#L24-L28
https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples_deepspeed/pretrain_llama2_distributed.sh

there are these weird default size configs:
```
HIDDEN_SIZE=2048 # e.g. llama-13b: 5120
FFN_HIDDEN_SIZE=5504 # e.g. llama-13b: 13824
NUM_LAYERS=24 # e.g. llama-13b: 40
NUM_HEADS=16 # e.g. llama-13b: 40
SEQ_LENGTH=2048
```
```
HIDDEN_SIZE=2048 # e.g. llama-13b: 5120
FFN_HIDDEN_SIZE=5504 # e.g. llama-13b: 13824
NUM_LAYERS=24 # e.g. llama-13b: 40
NUM_HEADS=16 # e.g. llama-13b: 40
SEQ_LENGTH=2048
NUM_KV_HEADS=4 # llama2 70B uses GQA
```
these do not match any public model sizes (7b is 4k); are they meant for some hypothetical 3B model?

**Comment by zdaiot** [comment]
@152334H Hello, have you solved it?
