### ISSUE TITLE
ZERO_STAGE doesn't seem to be working

### ISSUE THREAD

**Issue by hhhh12345678** [microsoft/Megatron-DeepSpeed#239]
when I run the config as below:
`WORLD_SIZE=8,TP=1,PP=4,GLOBAL_BATCH_SIZE=8,ZERO_STAGE=0`

I got the gpu status:
<img width="711" alt="截屏2023-09-01 16 57 13" src="https://github.com/microsoft/Megatron-DeepSpeed/assets/43569143/5c37b24d-e2c9-42fe-960b-a1c4e8a20c24">

changes the `ZERO_STAGE=0` into `ZERO_STAGE=1`
I got:
<img width="660" alt="截屏2023-09-01 16 54 56" src="https://github.com/microsoft/Megatron-DeepSpeed/assets/43569143/29d67f83-f3ec-4773-87a6-46224b0c4b20">

Logically, ZERO will significantly reduce the GPU memory occupied by the optimizer state.
But in my cases, it doesn't seem to be working？

I'm not sure if it was my operational mistake, in fact, I just made the necessary modifications in `examples_deepspeed/pretrain_llama2_distributed.sh`

**Comment by imh966** [comment]
> when I run the config as below: `WORLD_SIZE=8,TP=1,PP=4,GLOBAL_BATCH_SIZE=8,ZERO_STAGE=0`
> 
> I got the gpu status: <img alt="截屏2023-09-01 16 57 13" width="711" src="https://user-images.githubusercontent.com/43569143/264975892-5c37b24d-e2c9-42fe-960b-a1c4e8a20c24.png">
> 
> changes the `ZERO_STAGE=0` into `ZERO_STAGE=1` I got: <img alt="截屏2023-09-01 16 54 56" width="660" src="https://user-images.githubusercontent.com/43569143/264977658-29d67f83-f3ec-4773-87a6-46224b0c4b20.png">
> 
> Logically, ZERO will significantly reduce the GPU memory occupied by the optimizer state. But in my cases, it doesn't seem to be working？
> 
> I'm not sure if it was my operational mistake, in fact, I just made the necessary modifications in `examples_deepspeed/pretrain_llama2_distributed.sh`

https://github.com/microsoft/DeepSpeed/issues/1835
I think this issue from deepspeed may help you. It seems that ZeRO1 is enabled when enables bf16.

**Comment by imh966** [comment]
https://github.com/microsoft/DeepSpeed/issues/1835
I think this issue from deepspeed may help you. It seems that ZeRO1 is enabled when enables bf16.

**Comment by heroes999** [comment]
Did you encounter this error? I'm using examples_deepspeed/pretrain_llama_distributed.sh, with TP=1/PP=2 + bf16 enabled + zero_stage:0 in 4*A100 server, but I got the above errors. @hhhh12345678 
`/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [124,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "/home/wye/Megatron-DeepSpeed/pretrain_gpt.py", line 354, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "/home/wye/Megatron-DeepSpeed/megatron/training.py", line 200, in pretrain
    iteration = train(forward_step_func,
  File "/home/wye/Megatron-DeepSpeed/megatron/training.py", line 1137, in train
    train_step(forward_step_func,
  File "/home/wye/Megatron-DeepSpeed/megatron/training.py", line 641, in train_step
    loss = model[0].train_batch(data_iter=data_iterator)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 347, in train_batch
    self._exec_schedule(sched)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 1336, in _exec_schedule
    self._exec_instr(**cmd.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 643, in _exec_forward_pass
    outputs = super().forward(inputs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1801, in forward
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/module.py", line 349, in forward
    x = func(forward_input)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/module.py", line 342, in exec_func
    inputs = layer(inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wye/Megatron-DeepSpeed/megatron/model/transformer.py", line 1397, in forward
    return super().forward(hidden_states, attention_mask, **kwargs, rotary_pos_emb=rotary_pos_emb)[0]
  File "/home/wye/Megatron-DeepSpeed/megatron/model/transformer.py", line 1243, in forward
    self.self_attention(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wye/Megatron-DeepSpeed/megatron/model/transformer.py", line 688, in forward
    mixed_x_layer, _ = self.query_key_value(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wye/Megatron-DeepSpeed/megatron/core/tensor_parallel/layers.py", line 595, in forward
    output_parallel = linear_with_grad_accumulation_and_async_allreduce(
  File "/home/wye/Megatron-DeepSpeed/megatron/core/tensor_parallel/layers.py", line 422, in linear_with_grad_accumulation_and_async_allreduce
    return LinearWithGradAccumulationAndAsyncCommunication.apply(*args)
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/amp/autocast_mode.py", line 98, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/wye/Megatron-DeepSpeed/megatron/core/tensor_parallel/layers.py", line 243, in forward
    output = torch.matmul(total_input, weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

**Comment by yuqie** [comment]
> Did you encounter this error? I'm using examples_deepspeed/pretrain_llama_distributed.sh, with TP=1/PP=2 + bf16 enabled + zero_stage:0 in 4*A100 server, but it failed with the following errors. @hhhh12345678
> 
> ```
> /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [124,0,0] Assertion srcIndex < srcSelectDimSize failed.
> 
> /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [125,0,0] Assertion srcIndex < srcSelectDimSize failed.
> 
> /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [126,0,0] Assertion srcIndex < srcSelectDimSize failed.
> 
> /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [127,0,0] Assertion srcIndex < srcSelectDimSize failed.
> 
> Traceback (most recent call last):
>   File "/Megatron-DeepSpeed/pretrain_gpt.py", line 354, in <module>
>     pretrain(train_valid_test_datasets_provider,
>   File "/Megatron-DeepSpeed/megatron/training.py", line 200, in pretrain
>     iteration = train(forward_step_func,
>   File "/Megatron-DeepSpeed/megatron/training.py", line 1137, in train
>     train_step(forward_step_func,
>   File "/Megatron-DeepSpeed/megatron/training.py", line 641, in train_step
>     loss = model[0].train_batch(data_iter=data_iterator)
>   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 347, in train_batch
>     self._exec_schedule(sched)
>   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 1336, in _exec_schedule
>     self._exec_instr(**cmd.kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 643, in _exec_forward_pass
>     outputs = super().forward(inputs)
>   File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
>     ret_val = func(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1801, in forward
>     loss = self.module(*inputs, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/module.py", line 349, in forward
>     x = func(forward_input)
>   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/module.py", line 342, in exec_func
>     inputs = layer(inputs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/Megatron-DeepSpeed/megatron/model/transformer.py", line 1397, in forward
>     return super().forward(hidden_states, attention_mask, **kwargs, rotary_pos_emb=rotary_pos_emb)[0]
>   File "//Megatron-DeepSpeed/megatron/model/transformer.py", line 1243, in forward
>     self.self_attention(
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/Megatron-DeepSpeed/megatron/model/transformer.py", line 688, in forward
>     mixed_x_layer, _ = self.query_key_value(hidden_states)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/Megatron-DeepSpeed/megatron/core/tensor_parallel/layers.py", line 595, in forward
>     output_parallel = linear_with_grad_accumulation_and_async_allreduce(
>   File "/Megatron-DeepSpeed/megatron/core/tensor_parallel/layers.py", line 422, in linear_with_grad_accumulation_and_async_allreduce
>     return LinearWithGradAccumulationAndAsyncCommunication.apply(*args)
>   File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 506, in apply
>     return super().apply(*args, **kwargs)  # type: ignore[misc]
>   File "/usr/local/lib/python3.10/dist-packages/torch/cuda/amp/autocast_mode.py", line 98, in decorate_fwd
>     return fwd(*args, **kwargs)
>   File "/Megatron-DeepSpeed/megatron/core/tensor_parallel/layers.py", line 243, in forward
>     output = torch.matmul(total_input, weight.t())
> RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling cublasCreate(handle)
> terminate called after throwing an instance of 'c10::Error'
>   what():  CUDA error: device-side assert triggered
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
> ```

have you solved it? I also encountered this error

**Comment by asr-sheep1** [comment]
> > Did you encounter this error? I'm using examples_deepspeed/pretrain_llama_distributed.sh, with TP=1/PP=2 + bf16 enabled + zero_stage:0 in 4*A100 server, but it failed with the following errors. @hhhh12345678
> > ```
> > /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [124,0,0] Assertion srcIndex < srcSelectDimSize failed.
> > 
> > /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [125,0,0] Assertion srcIndex < srcSelectDimSize failed.
> > 
> > /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [126,0,0] Assertion srcIndex < srcSelectDimSize failed.
> > 
> > /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [127,0,0] Assertion srcIndex < srcSelectDimSize failed.
> > 
> > Traceback (most recent call last):
> >   File "/Megatron-DeepSpeed/pretrain_gpt.py", line 354, in <module>
> >     pretrain(train_valid_test_datasets_provider,
> >   File "/Megatron-DeepSpeed/megatron/training.py", line 200, in pretrain
> >     iteration = train(forward_step_func,
> >   File "/Megatron-DeepSpeed/megatron/training.py", line 1137, in train
> >     train_step(forward_step_func,
> >   File "/Megatron-DeepSpeed/megatron/training.py", line 641, in train_step
> >     loss = model[0].train_batch(data_iter=data_iterator)
> >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 347, in train_batch
> >     self._exec_schedule(sched)
> >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 1336, in _exec_schedule
> >     self._exec_instr(**cmd.kwargs)
> >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 643, in _exec_forward_pass
> >     outputs = super().forward(inputs)
> >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
> >     ret_val = func(*args, **kwargs)
> >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1801, in forward
> >     loss = self.module(*inputs, **kwargs)
> >   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
> >     return forward_call(*args, **kwargs)
> >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/module.py", line 349, in forward
> >     x = func(forward_input)
> >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/module.py", line 342, in exec_func
> >     inputs = layer(inputs)
> >   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
> >     return forward_call(*args, **kwargs)
> >   File "/Megatron-DeepSpeed/megatron/model/transformer.py", line 1397, in forward
> >     return super().forward(hidden_states, attention_mask, **kwargs, rotary_pos_emb=rotary_pos_emb)[0]
> >   File "//Megatron-DeepSpeed/megatron/model/transformer.py", line 1243, in forward
> >     self.self_attention(
> >   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
> >     return forward_call(*args, **kwargs)
> >   File "/Megatron-DeepSpeed/megatron/model/transformer.py", line 688, in forward
> >     mixed_x_layer, _ = self.query_key_value(hidden_states)
> >   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
> >     return forward_call(*args, **kwargs)
> >   File "/Megatron-DeepSpeed/megatron/core/tensor_parallel/layers.py", line 595, in forward
> >     output_parallel = linear_with_grad_accumulation_and_async_allreduce(
> >   File "/Megatron-DeepSpeed/megatron/core/tensor_parallel/layers.py", line 422, in linear_with_grad_accumulation_and_async_allreduce
> >     return LinearWithGradAccumulationAndAsyncCommunication.apply(*args)
> >   File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 506, in apply
> >     return super().apply(*args, **kwargs)  # type: ignore[misc]
> >   File "/usr/local/lib/python3.10/dist-packages/torch/cuda/amp/autocast_mode.py", line 98, in decorate_fwd
> >     return fwd(*args, **kwargs)
> >   File "/Megatron-DeepSpeed/megatron/core/tensor_parallel/layers.py", line 243, in forward
> >     output = torch.matmul(total_input, weight.t())
> > RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling cublasCreate(handle)
> > terminate called after throwing an instance of 'c10::Error'
> >   what():  CUDA error: device-side assert triggered
> > CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> > For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> > Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
> > ```
> 
> have you solved it? I also encountered this error

have you solved it? I also encountered this error, when tp=1.

**Comment by 9LLPPLL6** [comment]
> > > Did you encounter this error? I'm using examples_deepspeed/pretrain_llama_distributed.sh, with TP=1/PP=2 + bf16 enabled + zero_stage:0 in 4*A100 server, but it failed with the following errors. [@hhhh12345678](https://github.com/hhhh12345678)
> > > ```
> > > /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [124,0,0] Assertion srcIndex < srcSelectDimSize failed.
> > > 
> > > /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [125,0,0] Assertion srcIndex < srcSelectDimSize failed.
> > > 
> > > /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [126,0,0] Assertion srcIndex < srcSelectDimSize failed.
> > > 
> > > /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [127,0,0] Assertion srcIndex < srcSelectDimSize failed.
> > > 
> > > Traceback (most recent call last):
> > >   File "/Megatron-DeepSpeed/pretrain_gpt.py", line 354, in <module>
> > >     pretrain(train_valid_test_datasets_provider,
> > >   File "/Megatron-DeepSpeed/megatron/training.py", line 200, in pretrain
> > >     iteration = train(forward_step_func,
> > >   File "/Megatron-DeepSpeed/megatron/training.py", line 1137, in train
> > >     train_step(forward_step_func,
> > >   File "/Megatron-DeepSpeed/megatron/training.py", line 641, in train_step
> > >     loss = model[0].train_batch(data_iter=data_iterator)
> > >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 347, in train_batch
> > >     self._exec_schedule(sched)
> > >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 1336, in _exec_schedule
> > >     self._exec_instr(**cmd.kwargs)
> > >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 643, in _exec_forward_pass
> > >     outputs = super().forward(inputs)
> > >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
> > >     ret_val = func(*args, **kwargs)
> > >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1801, in forward
> > >     loss = self.module(*inputs, **kwargs)
> > >   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
> > >     return forward_call(*args, **kwargs)
> > >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/module.py", line 349, in forward
> > >     x = func(forward_input)
> > >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/module.py", line 342, in exec_func
> > >     inputs = layer(inputs)
> > >   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
> > >     return forward_call(*args, **kwargs)
> > >   File "/Megatron-DeepSpeed/megatron/model/transformer.py", line 1397, in forward
> > >     return super().forward(hidden_states, attention_mask, **kwargs, rotary_pos_emb=rotary_pos_emb)[0]
> > >   File "//Megatron-DeepSpeed/megatron/model/transformer.py", line 1243, in forward
> > >     self.self_attention(
> > >   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
> > >     return forward_call(*args, **kwargs)
> > >   File "/Megatron-DeepSpeed/megatron/model/transformer.py", line 688, in forward
> > >     mixed_x_layer, _ = self.query_key_value(hidden_states)
> > >   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
> > >     return forward_call(*args, **kwargs)
> > >   File "/Megatron-DeepSpeed/megatron/core/tensor_parallel/layers.py", line 595, in forward
> > >     output_parallel = linear_with_grad_accumulation_and_async_allreduce(
> > >   File "/Megatron-DeepSpeed/megatron/core/tensor_parallel/layers.py", line 422, in linear_with_grad_accumulation_and_async_allreduce
> > >     return LinearWithGradAccumulationAndAsyncCommunication.apply(*args)
> > >   File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 506, in apply
> > >     return super().apply(*args, **kwargs)  # type: ignore[misc]
> > >   File "/usr/local/lib/python3.10/dist-packages/torch/cuda/amp/autocast_mode.py", line 98, in decorate_fwd
> > >     return fwd(*args, **kwargs)
> > >   File "/Megatron-DeepSpeed/megatron/core/tensor_parallel/layers.py", line 243, in forward
> > >     output = torch.matmul(total_input, weight.t())
> > > RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling cublasCreate(handle)
> > > terminate called after throwing an instance of 'c10::Error'
> > >   what():  CUDA error: device-side assert triggered
> > > CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> > > For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> > > Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
> > > ```
> > 
> > 
> > CUDA error: CUBLAS_STATUS_NOT_INITIALIZED 
> 
> have you solved it? I also encountered this error, when tp=1.



> > > Did you encounter this error? I'm using examples_deepspeed/pretrain_llama_distributed.sh, with TP=1/PP=2 + bf16 enabled + zero_stage:0 in 4*A100 server, but it failed with the following errors. [@hhhh12345678](https://github.com/hhhh12345678)
> > > ```
> > > /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [124,0,0] Assertion srcIndex < srcSelectDimSize failed.
> > > 
> > > /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [125,0,0] Assertion srcIndex < srcSelectDimSize failed.
> > > 
> > > /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [126,0,0] Assertion srcIndex < srcSelectDimSize failed.
> > > 
> > > /opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [127,0,0] Assertion srcIndex < srcSelectDimSize failed.
> > > 
> > > Traceback (most recent call last):
> > >   File "/Megatron-DeepSpeed/pretrain_gpt.py", line 354, in <module>
> > >     pretrain(train_valid_test_datasets_provider,
> > >   File "/Megatron-DeepSpeed/megatron/training.py", line 200, in pretrain
> > >     iteration = train(forward_step_func,
> > >   File "/Megatron-DeepSpeed/megatron/training.py", line 1137, in train
> > >     train_step(forward_step_func,
> > >   File "/Megatron-DeepSpeed/megatron/training.py", line 641, in train_step
> > >     loss = model[0].train_batch(data_iter=data_iterator)
> > >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 347, in train_batch
> > >     self._exec_schedule(sched)
> > >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 1336, in _exec_schedule
> > >     self._exec_instr(**cmd.kwargs)
> > >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 643, in _exec_forward_pass
> > >     outputs = super().forward(inputs)
> > >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
> > >     ret_val = func(*args, **kwargs)
> > >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1801, in forward
> > >     loss = self.module(*inputs, **kwargs)
> > >   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
> > >     return forward_call(*args, **kwargs)
> > >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/module.py", line 349, in forward
> > >     x = func(forward_input)
> > >   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/module.py", line 342, in exec_func
> > >     inputs = layer(inputs)
> > >   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
> > >     return forward_call(*args, **kwargs)
> > >   File "/Megatron-DeepSpeed/megatron/model/transformer.py", line 1397, in forward
> > >     return super().forward(hidden_states, attention_mask, **kwargs, rotary_pos_emb=rotary_pos_emb)[0]
> > >   File "//Megatron-DeepSpeed/megatron/model/transformer.py", line 1243, in forward
> > >     self.self_attention(
> > >   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
> > >     return forward_call(*args, **kwargs)
> > >   File "/Megatron-DeepSpeed/megatron/model/transformer.py", line 688, in forward
> > >     mixed_x_layer, _ = self.query_key_value(hidden_states)
> > >   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
> > >     return forward_call(*args, **kwargs)
> > >   File "/Megatron-DeepSpeed/megatron/core/tensor_parallel/layers.py", line 595, in forward
> > >     output_parallel = linear_with_grad_accumulation_and_async_allreduce(
> > >   File "/Megatron-DeepSpeed/megatron/core/tensor_parallel/layers.py", line 422, in linear_with_grad_accumulation_and_async_allreduce
> > >     return LinearWithGradAccumulationAndAsyncCommunication.apply(*args)
> > >   File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 506, in apply
> > >     return super().apply(*args, **kwargs)  # type: ignore[misc]
> > >   File "/usr/local/lib/python3.10/dist-packages/torch/cuda/amp/autocast_mode.py", line 98, in decorate_fwd
> > >     return fwd(*args, **kwargs)
> > >   File "/Megatron-DeepSpeed/megatron/core/tensor_parallel/layers.py", line 243, in forward
> > >     output = torch.matmul(total_input, weight.t())
> > > RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling cublasCreate(handle)
> > > terminate called after throwing an instance of 'c10::Error'
> > >   what():  CUDA error: device-side assert triggered
> > > CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> > > For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> > > Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
> > > ```
> > 
> > 
> > have you solved it? I also encountered this error
> 
> have you solved it? I also encountered this error, when tp=1.

have you solved it? I also encountered this error
