### ISSUE TITLE
Support TransformerEngine

### ISSUE THREAD

**Issue by okoge-kaz** [microsoft/Megatron-DeepSpeed#317]
## Overview

Megatron-DeepSpeed does not appear to support learning with TransformerEngine. This is critical as our team is currently looking to use Megatron-DeepSpeed. Could you please implement this?

## Detail

if I set `transformer-impl transformer_engine`, the following part checks if the model type is GPTModel or not, and if it is used with DeepSpeed functionality, the job will fail with assert, so it cannot be trained.
https://github.com/microsoft/Megatron-DeepSpeed/blob/main/megatron/training.py#L373-L377

## Background

Megatron-LM supports the use of the TransformerEngine as follows
https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/arguments.py#L497-L499

However, the Megatron-LM implementation is compatible with an older version of the Transformer Engine and will not work with the latest version, so the following changes must be made.

`Megatron-LM/megatron/model/transformer.py:L1504-1505`
```diff
                    get_rng_state_tracker=tensor_parallel.get_cuda_rng_tracker,
                    fuse_wgrad_accumulation=config.gradient_accumulation_fusion,
-                   apply_query_key_layer_scaling=config.apply_query_key_layer_scaling,
-                  attention_softmax_in_fp32=config.attention_softmax_in_fp32,
```

FYI:  In the current version, the suggestion that these two arguments need to be removed is written below

> The TransformerLayer arguments attention_softmax_in_fp32 and apply_query_key_layer_scaling are deprecated, and will be removed in a future release. The default behavior is as if those arguments were set to True.

TransformerEngine 0.9.0(beta): https://docs.nvidia.com/deeplearning/transformer-engine-releases/release-0.9.0/release-notes/index.html

**Comment by jomayeri** [comment]
@okoge-kaz What non-GPT model are you trying to train?
