### ISSUE TITLE
The pile and its BookCorpus subset are not available

### ISSUE THREAD

**Issue by xvanQ** [microsoft/Megatron-DeepSpeed#319]
The pile and its BookCorpus subset are not available. I am also unable to download this dataset for pretrain gpt. Is there any other dataset to replace it, or is there a backup of the previous dataset available for download? I would like to run examples of zero-2 and zero-3.

**Comment by xvanQ** [comment]
https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/main/start_fast.md#2-data

**Comment by xvanQ** [comment]
https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/main/start_fast.md#2-data
According to the data section in the example document, preprocess the data and change it to the corresponding data path in config, at least it can run.

**Comment by loadams** [comment]
The original bookcorpus dataset is no longer available, but there are equivalents and steps to reproduce the data:

https://towardsdatascience.com/replicating-the-toronto-bookcorpus-dataset-a-write-up-44ea7b87d091
https://huggingface.co/datasets/bookcorpus
