### ISSUE TITLE
The link (https://the-eye.eu/public/AI/pile_neox/data/BookCorpusDataset_text_document.bin ) has expired.

### ISSUE THREAD

**Issue by HIT-cwh** [microsoft/Megatron-DeepSpeed#342]
The link (https://the-eye.eu/public/AI/pile_neox/data/BookCorpusDataset_text_document.bin) has expired.
![image](https://github.com/microsoft/Megatron-DeepSpeed/assets/41630003/916ca98b-0324-44de-928a-5e184e1b7a8b)

**Comment by loadams** [comment]
The original bookcorpus dataset is no longer available, but there are equivalents and steps to reproduce the data:

https://towardsdatascience.com/replicating-the-toronto-bookcorpus-dataset-a-write-up-44ea7b87d091
https://huggingface.co/datasets/bookcorpus
