### ISSUE TITLE
How efficient is the BERT and T5 code?

### ISSUE THREAD

**Issue by StellaAthena** [microsoft/Megatron-DeepSpeed#46]
I’m looking into training roBERTa and T5-style models but I wasn’t able to find much on their performance in Megatron DS. I know that at one point they were a WIP, but what’s the latest on them?

**Comment by conglongli** [comment]
Hi @StellaAthena, we have added BERT support (with example scripts and reference perf number) in this PR https://github.com/microsoft/Megatron-DeepSpeed/pull/75 and will merge it soon. Feel free to reopen this issue or create new issue if you have additional questions about this case.
