### ISSUE TITLE
[Bug]Load checkpoint err using pretrain_bert.py with Megatron

### ISSUE THREAD

**Issue by kisseternity** [microsoft/Megatron-DeepSpeed#61]
Hello, when I was using deepspeed to save and load checkpoints, I got this error.
![image](https://user-images.githubusercontent.com/15059072/177459926-b78edf9e-4364-4f3b-835d-bf0adaf7955e.png)

As saving checkpoints is fine, I think the _language_model_ key is not saved in that process.

**Comment by conglongli** [comment]
See discussions in https://github.com/microsoft/Megatron-DeepSpeed/pull/62

**Comment by kisseternity** [comment]
> See discussions in #62

Thanks for that.
